frase= 'Curso em Video Python'
print(frase[9:21])
print(frase[9:21:2])
print(frase[:5])
print(frase[15:])
print(frase[9::3])
print(len(frase))
print(frase.count('o'))
print(frase.count('o',0,13))
print(frase.find('deo'))
print(frase.find('Android'))
print('Curso' in frase)
print(frase.replace('Python','Android'))
print(frase.upper())
print(frase.lower())
print(frase.capitalize())
print(frase.title())
frase3 = frase.split()
print(frase3)
print('-'.join(frase3))
print('Para mostrar só o primeiro item da lista depois do split por exemplo {} ou o último {} ou \nmostrar a terceira letra da terceira palavra {}'.format(frase3[0],frase3[3],frase3[2][2]))

print(20 * '=')
frase2 = '  Aprenda Python   '
print(frase2)
print(frase2.strip())
print(frase2.rstrip())
print(frase2.lstrip())

